/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#810081",
        "on-tertiary": "#323200",
        "surface-container-lowest": "#0e0e13",
        "on-surface-variant": "#b9cac9",
        "surface-container-low": "#1b1b20",
        "surface-container-highest": "#35343a",
        "surface-variant": "#35343a",
        "secondary-container": "#fe00fe",
        "on-primary-fixed-variant": "#004f4f",
        "primary-container": "#00fbfb",
        "surface-container-high": "#2a292f",
        "on-primary": "#003737",
        "surface-tint": "#00dddd",
        "primary": "#ffffff",
        "secondary-fixed": "#ffd7f5",
        "on-tertiary-fixed-variant": "#494900",
        "on-surface": "#e4e1e9",
        "inverse-primary": "#006a6a",
        "surface-bright": "#39393e",
        "tertiary-fixed-dim": "#cdcd00",
        "on-error": "#690005",
        "inverse-on-surface": "#303035",
        "on-primary-fixed": "#002020",
        "surface": "#131318",
        "on-primary-container": "#007070",
        "on-error-container": "#ffdad6",
        "on-background": "#e4e1e9",
        "on-secondary-fixed": "#380038",
        "surface-container": "#1f1f24",
        "error": "#ffb4ab",
        "tertiary-container": "#eaea00",
        "secondary-fixed-dim": "#ffabf3",
        "outline": "#839493",
        "inverse-surface": "#e4e1e9",
        "tertiary-fixed": "#eaea00",
        "tertiary": "#ffffff",
        "background": "#131318",
        "primary-fixed-dim": "#00dddd",
        "outline-variant": "#3a4a49",
        "on-secondary": "#5b005b",
        "error-container": "#93000a",
        "on-secondary-container": "#500050",
        "primary-fixed": "#00fbfb",
        "on-tertiary-fixed": "#1d1d00",
        "secondary": "#ffabf3",
        "surface-dim": "#131318",
        "on-tertiary-container": "#686800"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        lg: "2.5rem",
        unit: "4px",
        sm: "1rem",
        md: "1.5rem",
        xl: "4rem",
        margin: "32px",
        xs: "0.5rem",
        gutter: "24px"
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "label-caps": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-caps": ["14px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}